# Output Pane is horizontal and cleared
split.vertical=0
clear.before.execute=1

# Save all buffers for build
save.all.for.build=1

# Tab is 2 spaces
tabsize=2
indent.size=2
use.tabs=0

# Always use default monospace font
font.base=$(font.monospace)
font.small=$(font.monospace)
font.comment=$(font.monospace)
font.text=$(font.monospace)
font.text.comment=$(font.monospace)
font.embedded.base=$(font.monospace)
font.embedded.comment=$(font.monospace)
font.vbs=$(font.monospace)

# Line numbers
line.margin.visible=1
line.margin.width=4+
